# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Alexa\Google Drive\6. Semester\Mechatronisches Projekt\Kamera 3\GUI\MechPro\form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(1106, 670)
        self.centralwidget = QtWidgets.QWidget(MainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.TabLiveBild = QtWidgets.QTabWidget(self.centralwidget)
        self.TabLiveBild.setGeometry(QtCore.QRect(20, 20, 1071, 591))
        self.TabLiveBild.setTabBarAutoHide(False)
        self.TabLiveBild.setObjectName("TabLiveBild")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.BtnKameraTabStuerung = QtWidgets.QPushButton(self.tab)
        self.BtnKameraTabStuerung.setGeometry(QtCore.QRect(190, 30, 111, 24))
        self.BtnKameraTabStuerung.setObjectName("BtnKameraTabStuerung")
        self.LblKameraStartStopp = QtWidgets.QLabel(self.tab)
        self.LblKameraStartStopp.setGeometry(QtCore.QRect(40, 30, 131, 20))
        self.LblKameraStartStopp.setObjectName("LblKameraStartStopp")
        self.LblConNodeRed = QtWidgets.QLabel(self.tab)
        self.LblConNodeRed.setGeometry(QtCore.QRect(40, 100, 131, 16))
        self.LblConNodeRed.setObjectName("LblConNodeRed")
        self.LblConJetsonNano = QtWidgets.QLabel(self.tab)
        self.LblConJetsonNano.setGeometry(QtCore.QRect(40, 150, 141, 16))
        self.LblConJetsonNano.setObjectName("LblConJetsonNano")
        self.LblConKamera = QtWidgets.QLabel(self.tab)
        self.LblConKamera.setGeometry(QtCore.QRect(40, 250, 141, 16))
        self.LblConKamera.setObjectName("LblConKamera")
        self.LblConBWCloud = QtWidgets.QLabel(self.tab)
        self.LblConBWCloud.setGeometry(QtCore.QRect(40, 200, 141, 16))
        self.LblConBWCloud.setObjectName("LblConBWCloud")
        self.TabLiveBild.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.BtnKameraBild = QtWidgets.QPushButton(self.tab_2)
        self.BtnKameraBild.setGeometry(QtCore.QRect(910, 520, 131, 31))
        self.BtnKameraBild.setObjectName("BtnKameraBild")
        self.BtnKameraTabLiveBild = QtWidgets.QPushButton(self.tab_2)
        self.BtnKameraTabLiveBild.setGeometry(QtCore.QRect(760, 520, 131, 31))
        self.BtnKameraTabLiveBild.setObjectName("BtnKameraTabLiveBild")
        self.lcdTrackedbj = QtWidgets.QLCDNumber(self.tab_2)
        self.lcdTrackedbj.setGeometry(QtCore.QRect(970, 8, 64, 23))
        self.lcdTrackedbj.setObjectName("lcdTrackedbj")
        self.LblTracktObj = QtWidgets.QLabel(self.tab_2)
        self.LblTracktObj.setGeometry(QtCore.QRect(870, 10, 91, 16))
        self.LblTracktObj.setObjectName("LblTracktObj")
        self.TabLiveBild.addTab(self.tab_2, "")
        MainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 22))
        self.menubar.setObjectName("menubar")
        self.menuSteuerung = QtWidgets.QMenu(self.menubar)
        self.menuSteuerung.setObjectName("menuSteuerung")
        self.menuLive_Bild = QtWidgets.QMenu(self.menubar)
        self.menuLive_Bild.setObjectName("menuLive_Bild")
        MainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWin)
        self.statusbar.setObjectName("statusbar")
        MainWin.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSteuerung.menuAction())
        self.menubar.addAction(self.menuLive_Bild.menuAction())

        self.retranslateUi(MainWin)
        self.TabLiveBild.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "MainWin"))
        self.BtnKameraTabStuerung.setText(_translate("MainWin", "Kamera Starten"))
        self.LblKameraStartStopp.setText(_translate("MainWin", "Kamer starten/stoppen"))
        self.LblConNodeRed.setText(_translate("MainWin", "Connectivity Node-Red"))
        self.LblConJetsonNano.setText(_translate("MainWin", "Connectivity Jetson Nano"))
        self.LblConKamera.setText(_translate("MainWin", "Connectivity Kamera"))
        self.LblConBWCloud.setText(_translate("MainWin", "Connectivity BW-Cloud"))
        self.TabLiveBild.setTabText(self.TabLiveBild.indexOf(self.tab), _translate("MainWin", "Steuerung"))
        self.BtnKameraBild.setText(_translate("MainWin", "Kamerabild (Start/stop)"))
        self.BtnKameraTabLiveBild.setText(_translate("MainWin", "Kamera Starten"))
        self.LblTracktObj.setText(_translate("MainWin", "Erfasste Objekte"))
        self.TabLiveBild.setTabText(self.TabLiveBild.indexOf(self.tab_2), _translate("MainWin", "LiveBild"))
        self.menuSteuerung.setTitle(_translate("MainWin", "Steuerung"))
        self.menuLive_Bild.setTitle(_translate("MainWin", "Live-Bild"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWin = QtWidgets.QMainWindow()
    ui = Ui_MainWin()
    ui.setupUi(MainWin)
    MainWin.show()
    sys.exit(app.exec_())
